### ISSUE TITLE
C::ParseError on normal typedef

### ISSUE THREAD

**Issue by Hype-Labs** [oggy/cast#14]
I'm trying to parse an header file that includes `stdint`, but I'm getting a parse error and can't explain the reason. The `parse` method is raising at line 12 of the following code:

```
typedef __signed char int8_t;
typedef short int16_t;
typedef int int32_t;
typedef long long int64_t;

typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;


typedef int8_t int_least8_t;
```

And I get the following error message:

> c.y:593:in `parse': 12:0: parse error on ID (int_least8_t) (C::ParseError)

I don't see a reason why this would be an error. Is this a bug?

**Comment by Hype-Labs** [comment]
I got the reason, and it's the first line. The parser does not appear to handle `__signed`. Changing that line to the following appears to solve the problem:

`typedef signed char int8_t;`

Unfortunately this is not an option, as this is a system header.

**Comment by Hype-Labs** [comment]
It also applies to `__darwin_va_list`. The parser doesn't seem to handle types starting with double underscore.

**Comment by oggy** [comment]
The problem is that these aren't part of the C99 standard. There's some commentary in the readme under "parsing full programs." You can prime the parser with a list of these built in types with `C.parser.type_names << '__darwin_va_list'`. Less sure about `__signed`, but the preprocessor may knock that out; otherwise you'll need to do a little massaging prior to passing it to Cast.

**Comment by Hype-Labs** [comment]
Makes sense. The parser can't recognize platform specific types. I'll try using `type_names`. Thank you!
